# Generated by Django 6.0.3 on 2026-07-08 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0010_add_ai_view_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('base_url', models.CharField(help_text='Model endpoint, e.g. http://127.0.0.1:11434', max_length=255, unique=True)),
                ('model_name', models.CharField(help_text='Model tag, e.g. granite4:3b', max_length=128)),
                ('is_active', models.BooleanField(default=False, help_text='Only one model integration may be active.')),
                ('last_status', models.CharField(choices=[('unknown', 'Unknown'), ('connected', 'Connected'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='unknown', max_length=50)),
                ('last_status_message', models.TextField(blank=True)),
                ('last_status_at', models.DateTimeField(blank=True, null=True)),
                ('detected_models', models.TextField(blank=True, default='', help_text='Comma-separated models detected at the endpoint.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
    ]
