# Generated by Django 6.0.3 on 2026-07-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0011_modelintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelintegration',
            name='role',
            field=models.CharField(choices=[('generate', 'Generation'), ('classify', 'Classification')], default='generate', max_length=20),
        ),
        migrations.AlterField(
            model_name='modelintegration',
            name='base_url',
            field=models.CharField(help_text='Model endpoint, e.g. http://127.0.0.1:11434', max_length=255),
        ),
        migrations.AlterField(
            model_name='modelintegration',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this role endpoint is in use.'),
        ),
        migrations.AlterField(
            model_name='modelintegration',
            name='label',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
