services:

  postgres:
    image: "postgres:${POSTGRES_VERSION:-17.0-bookworm}"
    restart: always
    volumes:
      - $HOME/MobInspect/postgresql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/mobinspectDB_password
      - POSTGRES_DB=mobinspect
    networks:
        - mobinspect_network
    secrets:
      - mobinspectDB_password

  mobinspect:
    image: ${MOBINSPECT_IMAGE:-appdirsdev/mobinspect:latest}
    restart: always
    ports:
     - "8000:8000"
     - "1337:1337"
    volumes:
      - $HOME/MobInspect/mobinspect_data:/home/mobinspect/.MobInspect
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/mobinspectDB_password
      - POSTGRES_DB=mobinspect
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - MOBINSPECT_API_KEY_FILE=/run/secrets/mobinspect_api_key
    healthcheck:
      test: curl -f http://localhost:8000/login/ || exit 1
    depends_on:
      - postgres
    networks:
      - mobinspect_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    secrets:
      - mobinspectDB_password
      - mobinspect_api_key

networks:
  mobinspect_network:

secrets:
  mobinspectDB_password:
    external: true
  mobinspect_api_key:
    external: true
