services:

  postgres:
    image: "postgres:14"
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    volumes:
      - $HOME/MobInspect/postgresql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mobinspect
    networks:
      - mobinspect_network

  nginx:
    image: nginx:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M
    ports:
      - "80:4000"
      - "1337:4001"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mobinspect
    networks:
      - mobinspect_network

  djangoq:
    image: appdirsdev/mobinspect:latest
    build:
      context: ..
      dockerfile: Dockerfile
    restart: unless-stopped
    command: /home/mobinspect/mobinspect/scripts/qcluster.sh
    volumes:
      - $HOME/MobInspect/mobinspect_data:/home/mobinspect/.MobInspect
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mobinspect
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - postgres
    networks:
      - mobinspect_network

  mobinspect:
    image: appdirsdev/mobinspect:latest
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    tty: true
    volumes:
      - $HOME/MobInspect/mobinspect_data:/home/mobinspect/.MobInspect
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mobinspect
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - MOBINSPECT_ASYNC_ANALYSIS=1
    healthcheck:
      test: curl -f http://localhost:8000/login/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - postgres
      - djangoq
    networks:
      - mobinspect_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  mobinspect_network:
    driver: bridge
