# Generated by Django 6.0.3 on 2026-06-12 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0008_merge_rbac_leaves'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdbConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('host_port', models.CharField(help_text="Stored 'host:port' or '[ipv6]:port' for adb connect.", max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], default='android', max_length=10)),
                ('is_active', models.BooleanField(default=False, help_text='Only one connection per platform may be active.')),
                ('last_status', models.CharField(choices=[('unknown', 'Unknown'), ('connected', 'Connected'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='unknown', max_length=50)),
                ('last_status_message', models.TextField(blank=True)),
                ('last_status_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adb_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['platform', 'label'],
            },
        ),
    ]
