# Generated by Django 6.0.3 on 2026-07-18 08:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaticAnalyzer', '0004_aienrichment_anomalies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentscansdb',
            name='TIMESTAMP',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
