# Generated by Django 6.0.3 on 2026-07-08 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaticAnalyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEnrichment',
            fields=[
                ('MD5', models.CharField(default='', max_length=32, primary_key=True, serialize=False)),
                ('STATUS', models.CharField(default='pending', max_length=32)),
                ('EXEC_SUMMARY', models.TextField(default='')),
                ('FINDING_EXPLANATIONS', models.TextField(default=[])),
                ('SECRETS_TRIAGE', models.TextField(default='')),
                ('MODEL_USED', models.CharField(default='', max_length=128)),
                ('CREATED_AT', models.DateTimeField(default=django.utils.timezone.now)),
                ('UPDATED_AT', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
