# Generated by Django 6.0.3 on 2026-07-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaticAnalyzer', '0002_aienrichment'),
    ]

    operations = [
        migrations.AddField(
            model_name='aienrichment',
            name='RISK_CLASSIFICATION',
            field=models.TextField(default=[]),
        ),
    ]
