# Generated by Django 6.0.3 on 2026-07-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaticAnalyzer', '0003_aienrichment_risk_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='aienrichment',
            name='ANOMALIES',
            field=models.TextField(default=[]),
        ),
    ]
